# Generated by Django 4.1.7 on 2023-03-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0002_donation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name_plural': 'Institutions'},
        ),
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
